# Generated by Django 4.2.4 on 2023-08-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Lirstname',
            new_name='Lastname',
        ),
    ]
